### ISSUE TITLE
Change $breakpoints name and typography boilerplate

### ISSUE THREAD

**Issue by dlewand691** [zellwk/typi#3]
I'm using Foundation and the $breakpoints variable you have in Typi is conflicting. Should/could it be named to something else? $ty-breakpoints perhaps? 

Would also love to see a full "typographic boilerplate" example with best practices for using Typi applied. 

Thanks so much!

**Comment by zellwk** [comment]
It makes sense to use the `$breakpoints` map even with foundation because you'll automatically use the `$breakpoints` map within foundation. All you have to do is get the use the correct keys to get the values out of them. Why would you want to change it? 

If you really wanted to, you can change `$breakpoints` into something else within typi mixin calls. like this: `@include typi($font-map, $breakpoints: $another-breakpoint-map);

What do you mean by a full typographic boilerplate?

**Comment by zellwk** [comment]
Closing if there are no further questions
