### ISSUE TITLE
Removal of ff() and fw()

### ISSUE THREAD

**Issue by ThePeach** [zellwk/typi#42]
I've been using the `$typefaces` map for a while now in my project and created a simple enough mixin that was using `ff()` and `fw()` directly, that helped me quite a bit and noticed that recently it got removed.

Any reasons behind it? I know it was not "officially" documented, but I was wondering if there's any plan around it or if I should prepare for full removal, at the moment I've decided to just include the typography sass file directly.

Thanks for your time and the effort to support this library.

**Comment by zellwk** [comment]
Great question. I didn't notice other people were using `ff` and `fw`, since they weren't documented officially. So, I removed them. I'm curious, what mixin did you create for your persional use? 

I wanted to improve `fw`, and that improvement is going to come soon, but had some hiccups during the dev process, and I thought I could remove them first, since nobody was using them (I presumed, sorry!).

**Comment by ThePeach** [comment]
sorry for the late reply: so at the moment the mixin is as simple as this:
```
@mixin font($type, $weight: 'regular') {
  @include ff($type);
  @include fw($type, $weight);
}
```
which works and does what I need.
I do like the idea of having the `$typefaces` map, IMO it's useful, although somehow some part seems to be cryptic to me, e.g. `font-size-ratio`, but overall it's really nice to have.
The mixin I've got makes things a bit more easy for final dev that won't have to worry about weights or exact names for the font families to use.

**Comment by zellwk** [comment]
`$font-size-ratio` was for a trial thing I was running. I have thoughts about it still, so I'm going to leave this hanging for a while until I sort out my thoughts. In the meantime, if you want the typefaces may back, mind sending in a pull request?
